# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsernew():
  
  def setup_method(self, method):
    self.driver = webdriver.Chrome()  # Initialize the driver here
  
  def teardown_method(self, method):
    self.driver.quit()

  @pytest.fixture(scope="class")
  def driver(self):
    driver = webdriver.Chrome()
    driver.maximize_window()
    yield driver
    driver.quit()

  def test_user_new(self):
    self.driver.get("http://localhost:4200/login")
    self.driver.set_window_size(1128, 1142)
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-4 > div:nth-child(1)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("williams@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("admin123456")
    self.driver.find_element(By.CSS_SELECTOR, ".space-y-4:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-indigo-600").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "titulo_dashboard").click()
    self.driver.find_element(By.ID, "sidebar_usuario").click()
    self.driver.find_element(By.ID, "title_usarios").click()
    self.driver.find_element(By.ID, "button_nuevo").click()
    self.driver.find_element(By.ID, "nombreUser").click()
    self.driver.find_element(By.ID, "nombreUser").send_keys("Sebas9") 
    self.driver.find_element(By.ID, "apellidoUser").send_keys("Luque9")
    self.driver.find_element(By.ID, "documentoUser").send_keys("711111114") # unico.
    self.driver.find_element(By.ID, "telefonoUser").send_keys("911111112")
    self.driver.find_element(By.ID, "direccionUser").send_keys("av siempre viva 362")
    self.driver.find_element(By.ID, "emailUser").send_keys("sebas14@gmail.com") # unico.
    self.driver.find_element(By.ID, "passwordUser").send_keys("admin123456")
    self.driver.find_element(By.ID, "rolUser").click()
    time.sleep(2)
    dropdown = self.driver.find_element(By.ID, "rolUser")
    dropdown.find_element(By.XPATH, "//option[. = 'vendedor']").click()
    self.driver.find_element(By.ID, "tipoEntidad").click()
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-blue-800").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-popup").click()
    self.driver.find_element(By.ID, "swal2-html-container").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".w-3").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "title_usarios").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".py-3:nth-child(3)").click()


  def test_user_multiple(self):
    
    # Datos de los usuarios de prueba
    usuarios = [
      {
          "nombre": "Carlos-21",
          "apellido": "Gomez",
          "documento": "7111112-21",
          "telefono": "911111113",
          "direccion": "Calle 1",
          "email": "carlos-21@gmail.com",
          "password": "admin123456",
          "rol": "vendedor",
      },
      {
          "nombre": "Ana-21",
          "apellido": "Martinez",
          "documento": "7111113-21",
          "telefono": "911111114",
          "direccion": "Calle 2",
          "email": "ana-21@gmail.com",
          "password": "admin123456",
          "rol": "vendedor",
      },
      {
          "nombre": "Luis-21",
          "apellido": "Perez",
          "documento": "7111114-21",
          "telefono": "911111115",
          "direccion": "Calle 3",
          "email": "luis-21@gmail.com",
          "password": "admin123456",
          "rol": "vendedor",
      },
      {
          "nombre": "Maria-21",
          "apellido": "Lopez",
          "documento": "7111115-21",
          "telefono": "911111116",
          "direccion": "Calle 4",
          "email": "maria-21@gmail.com",
          "password": "admin123456",
          "rol": "vendedor",
      },
      {
          "nombre": "Pedro-21",
          "apellido": "Ramirez",
          "documento": "7111116-21",
          "telefono": "911111117",
          "direccion": "Calle 5",
          "email": "pedro-21@gmail.com",
          "password": "admin123456",
          "rol": "vendedor",
      }
    ]

    # Iterar sobre los usuarios y completar el formulario de registro
    for usuario in usuarios:
      self.driver.get("http://localhost:4200/login")
      self.driver.set_window_size(1128, 1142)
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".space-y-4 > div:nth-child(1)").click()
      self.driver.find_element(By.ID, "email").click()
      self.driver.find_element(By.ID, "email").send_keys("williams@gmail.com")
      self.driver.find_element(By.ID, "password").click()
      self.driver.find_element(By.ID, "password").send_keys("admin123456")
      self.driver.find_element(By.CSS_SELECTOR, ".space-y-4:nth-child(2)").click()
      self.driver.find_element(By.CSS_SELECTOR, ".bg-indigo-600").click()
      time.sleep(2)
      self.driver.find_element(By.ID, "titulo_dashboard").click()
      self.driver.find_element(By.ID, "sidebar_usuario").click()
      self.driver.find_element(By.ID, "title_usarios").click()
      self.driver.find_element(By.ID, "button_nuevo").click()
      self.driver.find_element(By.ID, "nombreUser").send_keys(usuario["nombre"])
      self.driver.find_element(By.ID, "apellidoUser").send_keys(usuario["apellido"])
      self.driver.find_element(By.ID, "documentoUser").send_keys(usuario["documento"])
      self.driver.find_element(By.ID, "telefonoUser").send_keys(usuario["telefono"])
      self.driver.find_element(By.ID, "direccionUser").send_keys(usuario["direccion"])
      self.driver.find_element(By.ID, "emailUser").send_keys(usuario["email"])
      self.driver.find_element(By.ID, "passwordUser").send_keys(usuario["password"])
      self.driver.find_element(By.ID, "rolUser").click()
      time.sleep(2)
      dropdown = self.driver.find_element(By.ID, "rolUser")
      dropdown.find_element(By.XPATH, "//option[. = 'vendedor']").click()
      self.driver.find_element(By.ID, "tipoEntidad").click()
      self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-blue-800").click()
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".swal2-popup").click()
      self.driver.find_element(By.ID, "swal2-html-container").click()
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".swal2-confirm").click()
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".w-3").click()
      time.sleep(1)
      self.driver.find_element(By.ID, "title_usarios").click()
      time.sleep(1)
      self.driver.find_element(By.CSS_SELECTOR, ".py-3:nth-child(3)").click()